// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhr2hj_eV4JGBIKumzxyYGH0tSAJwvjC8',
    appId: '1:252270208258:web:7f91cf9d30c1b6af9ace1b',
    messagingSenderId: '252270208258',
    projectId: 'savedriver-4c822',
    authDomain: 'savedriver-4c822.firebaseapp.com',
    storageBucket: 'savedriver-4c822.appspot.com',
    measurementId: 'G-YHMN51HB01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJcuEfRC7ZAQDbXkkpGRu2vWAG-pA_6M',
    appId: '1:252270208258:android:137b38782bee1a039ace1b',
    messagingSenderId: '252270208258',
    projectId: 'savedriver-4c822',
    storageBucket: 'savedriver-4c822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHnoCBIvvT3FUoD8qAH2QiWEfesdsmhGc',
    appId: '1:252270208258:ios:dbc6c4da1668def09ace1b',
    messagingSenderId: '252270208258',
    projectId: 'savedriver-4c822',
    storageBucket: 'savedriver-4c822.appspot.com',
    iosBundleId: 'com.example.projectf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHnoCBIvvT3FUoD8qAH2QiWEfesdsmhGc',
    appId: '1:252270208258:ios:dbc6c4da1668def09ace1b',
    messagingSenderId: '252270208258',
    projectId: 'savedriver-4c822',
    storageBucket: 'savedriver-4c822.appspot.com',
    iosBundleId: 'com.example.projectf',
  );
}
